apiVersion: v1
kind: ConfigMap
metadata:
  name: ${SERVICE_NAME}-config
  namespace: ${NAMESPACE}
data:
  APPLICATION_INSIGHTS_IKEY : "97f6a0e1-6be6-44b0-97bf-d03852b7791f"
  AUTH_PROVIDER_SERVICE_CLIENT_BASEURL : "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  SLOT : "PRODUCTION"
  REFORM_ENVIRONMENT : "aat"
  REFORM_SERVICE_NAME : "cp"
  REFORM_TEAM : "finrem"
  ENVIRONMENT_NAME : "aat"
  VAULTNAME : "finrem-aat"
  VAULTURI : "https://finrem-aat.vault.azure.net/"
  IDAM_S2S_URL : "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
  APPINSIGHTS_INSTRUMENTATIONKEY : "97f6a0e1-6be6-44b0-97bf-d03852b7791f"