name: finrem-cos
apiVersion: v1
home: https://github.com/hmcts/finrem-case-orchestration-service
version: 0.0.7
description: Financial Remedy Case Orchestration Service
maintainers:
  - name: HMCTS Financial Remedy Team
