name: finrem-cos
apiVersion: v2
home: https://github.com/hmcts/finrem-case-orchestration-service
version: 0.2.22
description: Financial Remedy Case Orchestration Service
maintainers:
  - name: HMCTS Financial Remedy Team
dependencies:
  - name: java
    version: 4.0.13
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
