name: finrem-cos
apiVersion: v2
home: https://github.com/hmcts/finrem-case-orchestration-service
version: 0.2.2
description: Financial Remedy Case Orchestration Service
maintainers:
  - name: HMCTS Financial Remedy Team
dependencies:
  - name: java
    version: ~3.4.5
    repository: '@hmctspublic'
