java:
  aadIdentityName: finrem
  ingressHost: "finrem-cos-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
  applicationPort: '9000'
  image: 'hmctspublic.azurecr.io/finrem-cos:latest'
  environment:
    AUTH_PROVIDER_SERVICE_CLIENT_BASEURL : "https://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    PRD_API_URL: "https://rd-professional-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_S2S_URL: "https://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DOCUMENT_GENERATOR_SERVICE_API_BASEURL: "https://finrem-dgcs-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    FINREM_NOTIFICATION_SERVICE_BASE_URL: "https://finrem-ns-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    PAYMENT_SERVICE_API_BASEURL: "https://finrem-ps-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    EVIDENCE_MANAGEMENT_SERVICE_BASEURL: "https://finrem-emca-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    ACA_SERVICE_API_BASEURL: "https://aac-manage-case-assignment-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CCD_DATA_STORE_API_BASEURL: "https://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_REDIRECT_URL: "https://finrem-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal/oauth2/callback"
  autoscaling:
    enabled: true
    maxReplicas: 4
    minReplicas: 2
    targetCPUUtilizationPercentage: 80 # Default is 80% target CPU utilization
  keyVaults:
    finrem:
      secrets:
        - name: app-insights-connection-string
          alias: app-insights-connection-string
        - name: finrem-case-orchestration-service-s2s-key
          alias: AUTH_PROVIDER_SERVICE_CLIENT_KEY
        - name: idam-secret
          alias: OAUTH2_CLIENT_FINREM
        - name: finrem-system-update-username
          alias: FINREM_SYSTEMUPDATE_USERNAME
        - name: finrem-system-update-password
          alias: FINREM_SYSTEMUPDATE_PASSWORD
        - name: finrem-idam-client-secret
          alias: FINREM_IDAM_CLIENT_SECRET
