java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FEATURE_CONTESTED_PRINT_DRAFT_ORDER_NOT_APPROVED: true
    FEATURE_CONTESTED_PRINT_GENERAL_ORDER: true
    FEATURE_SHARE_A_CASE: true
    FEATURE_RESPONDENT_JOURNEY: true
    FEATURE_OFFLINE_NOTIFICATIONS:true
  keyVaults:
    finrem:
      secrets:
        - finrem-case-orchestration-service-s2s-key
        - idam-secret
