java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FEATURE_RESPONDENT_JOURNEY: true
    FEATURE_CASEWORKER_NOC: true
    FEATURE_USE_USER_TOKEN: true
    FEATURE_SOLICITOR_NOC: true
