java:
  devcpuRequests: 250m
  devmemoryRequests: 1Gi
  devcpuLimits: 1
  devmemoryLimits: 1Gi
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FEATURE_CASEWORKER_NOC: true
    FEATURE_ASSIGN_CASE_ACCESS: true
    FEATURE_USE_USER_TOKEN: true
    FEATURE_SOLICITOR_NOC: true
    FEATURE_MANAGE_BUNDLE: true