java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FEATURE_CONTESTED_PRINT_DRAFT_ORDER_NOT_APPROVED: true
    FEATURE_CONTESTED_PRINT_GENERAL_ORDER: true
    FEATURE_CONTESTED_COURT_DETAILS_MIGRATION: true
    FEATURE_AUTOMATE_SEND_ORDER: true
    FEATURE_AUTOMATE_ASSIGN_JUDGE: true
    FEATURE_SHARE_A_CASE: true
    # Disabled secrets on preview ( remove this and override keyvaults when adding secrets needed for preview)
    SPRING_CLOUD_PROPERTIESVOLUME_ENABLED: false
