java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    FEATURE_APPROVED_CONSENT_ORDER_NOTIFICATION_LETTER: true
    FEATURE_HWF_SUCCESSFUL_NOTIFICATION_LETTER: true
    FEATURE_ASSIGNED_TO_JUDGE_NOTIFICATION_LETTER: true
    FEATURE_CONSENT_ORDER_NOT_APPROVED_APPLICANT_DOCUMENT_GENERATION: true
    FEATURE_CONTESTED_COURT_DETAILS_MIGRATION: true
